### ISSUE TITLE
excel will be reopened, how can i close & save ,after write - pending details

### ISSUE THREAD

**Issue by cenwenchu** [aisingapore/TagUI#1261] opened 2022-07-21 08:01 UTC
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/80797/180161587-57658bd5-f9e9-49aa-8b67-e3f2581c1fd7.png">

code：
[test.xlsx]Sheet1!A1 = [['中文', 'Test2', 9], [4, 5, 6]]
[test.xlsx]Sheet1!A2 = [['中文', 'Test', 9], [4, 5, 6]]
wait 3

**Comment by ruthtxh** [comment] 2022-07-22 10:03
Hi @cenwenchu can you share more on what do you mean by excel will be reopened?
Do you have any instance of excel opened before you run TagUI?
Also, are you on windows or macOS?

I tried running your code and am able to write to excel which saves the value and closes the application after the run.

**Comment by cenwenchu** [comment] 2022-07-25 04:06
@ruthtxh thanks,i run program on macOS, and code only as below:
[test.xlsx]Sheet1!A1 = [['中文', 'Test2', 9], [4, 5, 6]]
[test.xlsx]Sheet1!A2 = [['中文', 'Test', 9], [4, 5, 6]]
wait 3

run first line , will open chrome and open excel,
run second line, will info me ,it will reopen excel (but first line excel not save), so will alert "excel not save, reopen will lose content".

so i don't know how to open file  and save file , "[test.xlsx]Sheet1!A2 = [['中文', 'Test', 9], [4, 5, 6]]" as auto open or reopen excel file, and  no save and append open file command line.

**Comment by ruthtxh** [comment] 2022-07-26 04:48
@cenwenchu what version of TagUI are you running on? 

I tested your code on TagUI version 6.113 and it is able to programmatically open, save and close the file with the data written to it. Hence, I am unable to replicate your issue.

If you're not running on the latest version of TagUI, you can do `tagui update` in your terminal to update. If error still persists, you may look into the following:
1. Check your folder location of the excel file - which may deny read/write permission 
2. Check excel settings which may be causing the above behaviour

**Comment by kensoh** [comment] 2024-08-19 12:51
Closing but please ping back if this is still relevant or an issue.

**Closed by kensoh** 2024-08-19 12:51 UTC
Labels: query

**Comment by kaptsanovb** [comment] 2025-04-03 07:01
Hi, i am also having this issue - i have v6.114 and office 2016.
@kensoh (i am new to Github, is this the correct way to ping?)

**Comment by kensoh** [comment] 2025-04-03 07:47
Hi @kaptsanovb can you paste the code you use and tell me what problem do you see? I think the issue maybe the version of Excel you are using is too old and this feature doesn't work with it.

**Comment by kaptsanovb** [comment] 2025-04-03 11:33
For example:
```
[file.xslx]Sheet1!A1 = 1
[file.xslx]Sheet1!A2 = 1
```

When the second instruction is executed, this warning pops up:

![Image](https://github.com/user-attachments/assets/7d6e12a9-222e-46e7-bb99-72d3516fb4fb)
(you can see that the A1 cell has been set to 1)

If I press Yes, the file is overwritten with the new data, ignoring the old changes:
![Image](https://github.com/user-attachments/assets/7fb734ab-f05b-4704-a5dd-fcb5141b7a95)

**Comment by kensoh** [comment] 2025-04-28 09:37
It sounds like either Excel behaviour has changed or the Excel you are running isn't compatible. I haven't heard of this issue reported by other users. Basically TagUI use VB Script to control Excel, and for some reason, the VB Script command is interpreted by Excel as reopening a new file. I don't have any inputs for now other than seeing if other users have an issue to try to find a common root cause. Does this problem happen on your other laptops or computers?
