### ISSUE TITLE
error copy text  in Spanish �

### ISSUE THREAD

**Issue by Darkness99q** [aisingapore/TagUI#1347] opened 2023-05-15 15:05 UTC
hello, good day, i am writing to you because i have an important error when using the type of function of tagui. the database in spanish language has symbols that are not used in other languages. the most common are: "ñ", "á", "é", "í¨ "ó", "ú". the problem is that when executing the example code (type antonio martín ....) in the page it writes ant�nio mart�n. and to load this data in this way is something harmful. A more complete and real example of how tagui did this is the following:

Apoyar t�cnicamente los procesos archiv�sticos de administraci�n, organizaci�n, conservaci�n, consulta traslado, transferencias y dem�s operaciones t�cnicas requeridas, en el marco de la implementaci�n del grupo de gesti�n documental, en atenci�n a los est�ndares establecidos por la Agencia para la Reincorporaci�n y la Normalizaci�n �ARN- y por el Archivo General de la Naci�n � AGN -.

how I could correct it or if they can contemplate it in the future much better. Thank you very much

**Comment by ruthtxh** [comment] 2023-05-19 04:53
Hello @Darkness99q you can try this solution:
https://github.com/aisingapore/TagUI/issues/1082#issuecomment-884651987

**Comment by ruthtxh** [comment] 2023-05-19 04:54
Duplicate of #1082

**Closed by ruthtxh** 2023-05-19 04:54 UTC
Labels: query

**Comment by Darkness99q** [comment] 2023-05-25 20:36
> Duplicate of #1082

hello, there is some other alternative, the same thing keeps happening the error persists I leave part of the code below click /html/body/div[1]/div[1]/div/section[2]/div[2]/div[ 1]/a
wait 3
select //*[@id="DocumentType"] as CC
message = '`CEDULA` '
clipboard(message)
click //*[@id="DocumentNumber"]
keyboard [ctrl] v
type //*[@id="ContractNumber"] as [clear]`CONTRACT`
type //*[@id="Validity"] as [clear]2023
type //*[@id="SECOPProcess"] as [clear]`SECOP`
select //*[@id="IdClass"] as 2
select //*[@id="IdModality"] as 2
message = '`OBJECT` '
clipboard(message)
click //*[@id="ContractObject"]
keyboard [ctrl] v
message = '`OBLIGATIONS` '
clipboard(message)
click //*[@id="Obligations"]
