### ISSUE TITLE
Use Word Plug-in Some Error

### ISSUE THREAD

**Issue by petertsneg** [aisingapore/TagUI#1282] opened 2022-10-06 05:28 UTC
Word version : Word 2013

1.執行Update TagUI Error: (solved)
![wordPlugIn_updateError](https://user-images.githubusercontent.com/82127495/194221973-35fb945d-431d-43fb-9f32-1b5912a99b2c.png)
2.執行Live Mode Error: (solved)
![wordPlugIn_liveModeError](https://user-images.githubusercontent.com/82127495/194221980-15468e4e-6a45-40e5-8b4a-10f62c0686c8.png)
3.執行Run Error
![wordPlugIn_RunError](https://user-images.githubusercontent.com/82127495/194224702-e654bbad-fe56-471e-925b-b9f721b86d69.png)

**Comment by petertsneg** [comment] 2022-10-07 03:24
關於問題3,測試下列版本Word是可以正常執行,產出的.tag檔,也是UTF-8
Word 2007 : OK
Word 2010 : OK

**Comment by ruthtxh** [comment] 2022-10-14 02:17
Hi @petertsneg then this seems like the cause is language settings causes the files to save as UTF8-BOM instead of UTF. What language setting are you using that is causing this? I am unable to replicate this error.

**Comment by petertsneg** [comment] 2022-10-14 02:24
Hi @ruthtxh , 
language settings  Chinese (Traditional, Taiwan)
sorry for your troubles.

**Comment by petertsneg** [comment] 2022-10-18 01:18
Hi @ruthtxh ,
    What more information can I give you to help you replicate the problem?

**Comment by ruthtxh** [comment] 2022-10-18 03:35
Hi @petertsneg yes seems like Traditional Taiwan language forces notepad to save in UTF BOM format. We are seeing if this can be handled from the Addin without breaking its current functionality.

Meanwhile you may continue using TagUI without the Addin, or with another language setting.

**Comment by petertsneg** [comment] 2022-10-18 03:44
hi, @ruthtxh 
Great, I hope the problem can be solved, thank you~

**Comment by ruthtxh** [comment] 2022-11-01 16:09
Hi @petertsneg we have added the fix for this, please try it out and do let us know if there are any issues.
https://storage.googleapis.com/tagui-dependencies/TagUI%20WordAddIn/TagUIWordAddInSetupV3.16.zip

**Comment by petertsneg** [comment] 2022-11-02 00:32
hi @ruthtxh 
It's working fine , thank you~

**Closed** 2022-11-02 00:33 UTC
Labels: query
